config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  get '/salut(/:name)', to: 'pages#salut', as: 'salut'
  resources :posts
  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorie.rb
class Categorie < ApplicationRecord

  has_many :posts

  has_many :metas, as: :metaable

end

app/models/concerns/sluggable.rb
module Sluggable

  extend ActiveSupport::Concern

  included do
    before_validation :set_default_slug, on: [:create, :update], if: '!slug.nil?'

    private

    def set_default_slug
      if !self.name.nil? && !self.name.empty? && self.slug.empty?
        self.slug = name.parameterize
      end
    end
  end

end

app/models/meta.rb
class Meta < ApplicationRecord



  belongs_to :metaable, polymorphic: true

end

app/models/post.rb
class Post < ApplicationRecord

  #validates_with NameValidator


  include Sluggable

  belongs_to :categorie, counter_cache: true

  has_and_belongs_to_many :tags

  has_many :metas, as: :metaable

  scope :published, -> { where(online: 1) }

  scope :offline, -> (online){
    where(online: online) if online.is_a? Integer

  }


  validates :slug, format: { with: /\A[a-z0-9\-]+\z/ }, uniqueness: true


end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :danger
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_post, only: [:update, :destroy, :show, :edit]


  def index
    @session = session[:user_id]
    @categories = Categorie.all
  end

  def show

  end

  def edit

  end

  def update
    @cat.update(cat_params)
    redirect_to categories_path
  end

  def new
    @cat = Categorie.new
  end

  def create
    cat = Categorie.create(cat_params)

    redirect_to category_path(cat.id)
  end

  def destroy
    @cat.destroy

    redirect_to categories_path
  end


  private

  def cat_params
    params.require(:categorie).permit(:title, :description)
  end

  def set_post
    @cat = Categorie.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def salut
    @name = params[:name]
  end

  def home
    ContactMailer.contact(Post.first).deliver_later
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:update, :show, :edit, :destroy]
  #Action d'affichage de tous les articles
  def index
    session[:user_id] = {username: 'Sadate', id:3}
    cookies.encrypted[:username] = {
      value: "John",
      expires: 1.month.from_now
    }
    @posts = Post.includes(:categorie, :tags).all

    respond_to do |format|
      format.html {  }
      format.json { render json: @posts.as_json(only: [:name, :created_at, :id]) }
      format.xml { render xml: @posts }
    end
  end

  #Action d'affichage d'un article en particulier
  def show

  end

  #Action d'edition d'un article
  def edit

  end

  #Action de mis à jour d'un article
  def update
    if @post.update(post_params)
      redirect_to posts_path, success: "Article modifié avec succes"
    else
      render 'edit'
    end
  end

  #Action de creation d'un nouvel article
  def new
    @post = Post.new
  end

  #Action d'insertion d'un nouvel article
  def create
    post = Post.new(post_params)

    if post.valid?
      post.save
      redirect_to post_path(post.id), success: "Article crée avec succes"
    else
      @post = post
      render 'new'
    end
  end

  #Action pour detruire un element
  def destroy
    @post.destroy

    redirect_to posts_path, success: "Article supprimé avec succes"
  end

  #Action privée de recuperation des parametres transmis par les formulaires
  private

  def post_params
    params.require(:post).permit(:name, :content, :slug)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<h1>Editer la categorie</h1>

<%= form_for @cat do |f| %>

  <div class="form-group">
    <label for="">Titre de la categorie</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="">Description de la categorie</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Modifier la categorie</button>
  </div>


<% end%>

app/views/categories/index.html.erb
<h1>Liste des categories</h1>


<table class="table">
  <thead>
    <tr>
      <td>ID</td>
      <td>Title</td>
      <td>Description</td>
      <td>Actions</td>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |cat| %>
      <tr>
        <td><%= cat.id %></td>
        <td><%= cat.title %></td>
        <td><%= cat.description %></td>
        <td>
            <a href="<%= edit_category_path(cat.id) %>" class="btn btn-primary">Editer</a>
        </td>
        <td>
          <a href="<%= category_path(cat.id) %>" class="btn btn-danger" data-confirm = "Voulez vous vraiment suppromer cette categorie ?" data-method="DELETE">
            Supprimer</a>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<p>

  <a href="<%= new_category_path %>" class="btn btn-success">Creer une categorie</a>

</p>

app/views/categories/new.html.erb
<h1>Creer la categorie</h1>

<%= form_for @cat do |f| %>

  <div class="form-group">
    <label for="">Titre de la categorie</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label for="">Description de la categorie</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary">Creer la categorie</button>
  </div>


<% end%>

app/views/categories/show.html.erb
<h1><%= @cat.title %></h1>

<p><%= @cat.description %></p>

<p>
  <a href="<%= categories_path %>" class="btn btn-primary">Revenir aux categories</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'ROR Formation' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </head>

  <body>


    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Ruby On Rails</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%= posts_path %>">Articles</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="<%= categories_path %>">Categories</a>
          </li>


        </ul>
      </div>
    </nav>

    <div class="container" style="padding-top: 5rem">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/sidebar.html.erb
<div class="row">
  <% if content_for?(:sidebar) %>
  <div class="col-sm-8">
    <%= yield :content%>
  </div>

  <div class="col-sm-4">
    <%= yield :sidebar %>
  </div>

  <% else %>
    <div class="col-sm-12">
      <%= yield :content %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Bienvenue sur le site</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/pages/salut.html.erb
Salut <%= @name %> comment ça va ?

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <u>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </u>

  </div>
<% end %>

<%= form_for post do |f| %>

<div class="form-group">
  <label for="">Titre de l'article</label>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <label for="">URL de l'article</label>
  <%= f.text_field :slug, class: 'form-control' %>
</div>

<div class="form-group">
  <label for="">Contenu de l'article</label>
  <%= f.text_area :content, class: 'form-control' %>
</div>

<div class="form-group">
  <button type="submit" class="btn btn-primary">Modifier l'article</button>
</div>



<% end %>

app/views/posts/_post.html.erb
<h3><%= post.name %></h3>

<p><%= post.content %></p>

<% if post.categorie %>

  <p> <strong>Categorie : </strong><%= post.categorie.title %></p>

<% end %>

<% if !post.tags.empty? %>

<p>

  Tags :

  <%= post.tags.map(&:name).join(', ') %>

</p>

<% end %>


<p>

  <a href="<%= post_path(post.id) %>" class = "btn btn-primary">Lire la suite</a>

  <a href="<%= edit_post_path(post.id)%>" class = "btn btn-primary">Editer l'article</a>

  <a href="<%= post_path(post.id)%>" class="btn btn-danger" data-confirm = "Êtes vous sûr ?" data-method ="DELETE">Supprimer</a>

</p>

app/views/posts/edit.html.erb
<h1>Editer l'article</h1>

<%= url_for(p: 'marequete') %>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Articles du blog</h1>


<% @posts.each do |post| %>

  <%= render 'post', post: post%>

<% end %>

<p>
  <a href="<%= new_post_path %>" class="btn btn-success">Creer un nouvel article</a>
</p>

app/views/posts/new.html.erb
<h1>Creer un nouvel article</h1>


<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% content_for(:title, @post.name) %>

<% content_for :content do %>

  <h1><%= @post.name %></h1>

  <p><%= @post.content%></p>

  <p>
    <a href="<%= posts_path %>" class="btn btn-primary">Revenir aux articles</a>
  </p>

<% end %>

<% content_for :sidebar do %>

  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

<% end %>

<%= render template: 'layouts/sidebar'  %>